<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\domain\AriesContador.Core\AriesContador.Core.csproj" />
    <ProjectReference Include="..\..\infrastructure\AriesContador.Data\AriesContador.Data.csproj" />
  </ItemGroup>

</Project>
