<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3e541070-f7e6-4ef7-b343-1c9f1f32b0a3</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AriesContador.Core\AriesContador.Core.csproj" />
    <ProjectReference Include="..\CapaDatos\CapaDatos.csproj" />
    <ProjectReference Include="..\CapaEntidad\CapaEntidad.csproj" />
    <ProjectReference Include="..\CapaLogica\CapaLogica.csproj" />
  </ItemGroup>

</Project>
